name: Build

on:
  push:
    paths:
      - ".github/workflows/**"
      - "gzgspd/**"
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      BUILD_ENVS:
        description: "Build Environments (Space delimited)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libayatana-appindicator3-dev

      - name: Set up environments
        shell: bash
        run: |
          GOARCH=$(go env GOARCH)
          RUNNER_OS_LOWER=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "OUT_FILE=built/gzgspd-${RUNNER_OS_LOWER}-${GOARCH}-${GITHUB_REF_NAME}.exe" >> "$GITHUB_ENV"
            echo "OUT_FILE_NOD=built/gzgsp-${RUNNER_OS_LOWER}-${GOARCH}-${GITHUB_REF_NAME}.exe" >> "$GITHUB_ENV"
          else
            echo "OUT_FILE=built/gzgspd-${RUNNER_OS_LOWER}-${GOARCH}-${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          fi

          for env in $BUILD_ENVS; do
            echo "$env" >> "$GITHUB_ENV"
          done

      - name: Build
        shell: bash
        run: |
          cd gzgspd

          if [ ! -d "built" ]; then
            mkdir -vp "built"
          fi

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            go get github.com/akavel/rsrc
            rsrc -ico assets/logo.ico -o rsrc.syso
          fi

          go build -ldflags "-X main.Version=${GITHUB_REF_NAME}" -o "$OUT_FILE" -v .

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            go build -ldflags "-X main.Version=${GITHUB_REF_NAME} -H=windowsgui" -o "$OUT_FILE_NOD" -v .
          fi
        env:
          BUILD_ENVS: ${{ inputs.BUILD_ENVS }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-${{ matrix.os }}
          path: gzgspd/built/**

  release:
    # 只在 tag push 时执行
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: dist/**/*
          draft: true
          generate_release_notes: true
